#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.webui }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  labels:
    {{- include "free5gc-webui.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      nodePort: {{ .service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-webui.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
{{- end }}
---
{{- with .Values.global}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .webui.service.name }}
  labels:
    {{- include "free5gc-webui.labels" $ | nindent 4 }}
    project: {{ .projectName }}
    nf: {{ $.Values.webui.name }}
spec:
  type: {{ .webui.service.type }}
  ports:
    - port: {{ .webui.service.port }}
      targetPort: {{ .webui.service.port }}
      protocol: TCP
      name: webui-biling
  selector:
    {{- include "free5gc-webui.selectorLabels" $ | nindent 4 }}
    project: {{ .projectName }}
    nf: {{ $.Values.webui.name }}
{{- end }}