#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.n3iwf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free5gc-n3iwf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-n3iwf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-n3iwf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-n3iwf.n3iwfAnnotations" $ | nindent 8 }}
        k8s.v1.cni.cncf.io/networks: '[
        {{- if not $.Values.global.amf.service.ngap.enabled }}
            { "name": "{{ $.Values.global.n2network.name }}-{{ .name }}",
              "interface": "n2",
              "ips": [ "{{ .n2if.ipAddress }}/{{ $.Values.global.n2network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n2network.gatewayIP }}" ]
            },
        {{- end }}
            { "name": "{{ $.Values.global.n3network.name }}-{{ .name }}",
              "interface": "n3",
              "ips": [ "{{ .n3if.ipAddress }}/{{ $.Values.global.n3network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n3network.gatewayIP }}" ]
            },

            { "name": "{{ .ike.name }}-{{ .name }}",
              "interface": "ike",
              "ips": [ "{{ .ike.ipAddress }}/{{ .ike.cidr }}" ],
              "gateway": [ "{{ .ike.gatewayIP }}" ]
            }            
            ]'
        {{- if $.Values.n3iwf.configuration.metrics.enable }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ $.Values.n3iwf.configuration.metrics.port | quote }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/n3iwf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-n3iwf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-amf
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        command: 
          - "sh"
          - "-c"
          - |
            until ping -c 1 {{ $.Values.global.amf.n2if.ipAddress }}; do
              echo "waiting for AMF ({{ $.Values.global.amf.n2if.ipAddress }}) to be reachable..."
              sleep 2
            done
            echo "AMF is reachable, waiting 5s for service to be ready..."
            sleep 5
            echo "Proceeding to start N3IWF"
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        {{- if $.Values.n3iwf.configuration.metrics.enable }}
        ports:
        - name: metrics
          containerPort: {{ $.Values.n3iwf.configuration.metrics.port }}
        {{- end }}
        command: 
        - "sh"
        - "-c"
        - |
          # delete existing ip link if any
          ip link delete ipsec-default || true;
          # clean existing xfrm state and policy if any
          ip xfrm state flush || true;
          ip xfrm policy flush || true;
          ./config/n3iwf-ipsec.sh && ./n3iwf -c ./config/n3iwfcfg.yaml
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ include "free5gc-n3iwf.fullname" $ }}-volume
        - mountPath: {{ .volume.tlsmount }}
          name: {{ include "free5gc-n3iwf.fullname" $ }}-empty-volume
        - mountPath: {{ .volume.certmount }}
          name: {{ include "free5gc-n3iwf.fullname" $ }}-cert-pvc
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ include "free5gc-n3iwf.fullname" $ }}-volume
        projected:
          sources:
          - configMap:
              name: {{ .configmap.name }}
              items:
              - key: n3iwfcfg.yaml
                path: n3iwfcfg.yaml
              - key: n3iwf-ipsec.sh
                path: n3iwf-ipsec.sh
                mode: 0777
      - name: {{ include "free5gc-n3iwf.fullname" $ }}-empty-volume
        emptyDir: {}
      - name: {{ include "free5gc-n3iwf.fullname" $ }}-cert-pvc
        persistentVolumeClaim:
          claimName: cert-pvc
{{- end }}