#
# Software Name : free5gc-helm
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-pvc
  labels:
    project: {{ $.Values.global.projectName }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
