#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
{{- with .Values.psaupf2 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:
  upfcfg.yaml: |
    version: 1.0.3
    description: UPF initial local configuration

    # The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
    pfcp:
      addr: POD_IP_ADDR # IP addr for listening - replaced at runtime
      nodeID: POD_IP_ADDR # External IP or FQDN can be reached - replaced at runtime
      retransTimeout: 1s # retransmission timeout
      maxRetrans: 3 # the max number of retransmission

    gtpu:
      forwarder: gtp5g
      # The IP list of the N3/N9 interfaces on this UPF
      # If there are multiple connection, set addr to 0.0.0.0 or list all the addresses
      ifList:
        - addr: POD_IP_ADDR
          type: N9
          # name: upf.5gc.nctu.me
          # ifname: gtpif

    {{- toYaml .configuration | nindent 4 }}

  wrapper.sh: |
    #!/bin/sh
    set -e

    # Get Pod IP dynamically
    POD_IP=$(hostname -i | awk '{print $1}')
    echo "[wrapper] UPF2 (AnchorUPF2) Pod IP detected: $POD_IP"

    # Copy config to writable location
    cp {{ .volume.mount }}/upfcfg.yaml /tmp/upfcfg.yaml

    # Replace POD_IP_ADDR placeholder with actual Pod IP
    sed -i "s/POD_IP_ADDR/$POD_IP/g" /tmp/upfcfg.yaml

    echo "[wrapper] UPF2 PFCP config:"
    cat /tmp/upfcfg.yaml | grep -A3 "pfcp:"

    # Wait for upfgtp interface to be created by gtp5g module
    echo "[wrapper] Waiting for upfgtp interface..."
    for i in $(seq 1 30); do
      if ip link show upfgtp > /dev/null 2>&1; then
        echo "[wrapper] upfgtp interface is ready"
        break
      fi
      sleep 1
    done

    # Note: Route for UE subnet will be automatically added by UPF based on dnnList configuration
    # No need to manually add route here

    # Setup iptables for NAT (single interface mode - eth0)
    iptables -A FORWARD -j ACCEPT
    # NAT traffic from UE subnet going out via eth0 (for uplink to internet)
    iptables -t nat -A POSTROUTING -s {{ $.Values.global.uesubnet }} -o eth0 -j MASQUERADE

    {{- if $.Values.psaupf2.configmap.wrapperAdditionalCommands }}
    {{- $.Values.psaupf2.configmap.wrapperAdditionalCommands | toYaml | indent 2 }}
    {{- end }}

    echo "[wrapper] Starting UPF2 with dynamic config"
    exec /free5gc/upf -c /tmp/upfcfg.yaml

{{- end }}
{{- end }}
