#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gc-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  name: free5gc
  userPlaneArchitecture: ulcl  # possible values are "single" and "ulcl"
  uesubnet: 10.60.0.0/16  # UE IP address pool
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: "8000"
      nodePort: "30800"
  sbi:
    scheme: http
  
  # AMF Multus CNI Configuration
  amf:
    multus:
      enabled: false  # Default: disabled for cloud-native deployments
      n2if:  # NGAP interface (used when multus.enabled=true)
        ipAddress: 10.100.50.249
      n2network:
        enabled: true
        name: n2network
        type: ipvlan
        masterIf: eth0
        subnetIP: 10.100.50.248
        cidr: 29
        gatewayIP: 10.100.50.254
        excludeIP: 10.100.50.254
    service:
      ngap:
        enabled: true  # Enable NGAP service for external access
        name: amf-n2
        port: 38412
        nodeport: 31412
        protocol: SCTP
        type: NodePort
  
  # SMF Multus CNI Configuration
  smf:
    multus:
      enabled: false  # Default: disabled for cloud-native deployments
      n4if:  # PFCP interface (used when multus.enabled=true)
        ipAddress: 10.100.50.244
      n4network:
        enabled: true
        name: n4network
        type: ipvlan
        masterIf: eth0
        subnetIP: 10.100.50.240
        cidr: 29
        gatewayIP: 10.100.50.246
        excludeIP: 10.100.50.246
  
  # UPF Multus CNI Configuration
  upf:
    multus:
      enabled: false  # Default: disabled for cloud-native deployments
      # Static IP configurations for UPF instances (used when multus.enabled=true)
      upf:
        n3if:
          ipAddress: 10.100.50.233
        n4if:
          ipAddress: 10.100.50.241
        n6if:
          ipAddress: 10.0.2.11
      psaupf1:
        n4if:
          ipAddress: 10.100.50.242
        n6if:
          ipAddress: 10.0.2.12
        n9if:
          ipAddress: 10.100.50.225
      psaupf2:
        n4if:
          ipAddress: 10.100.50.243
        n6if:
          ipAddress: 10.0.2.13
        n9if:
          ipAddress: 10.100.50.226
      iupf1:
        n3if:
          ipAddress: 10.100.50.234
        n4if:
          ipAddress: 10.100.50.245
        n6if:
          ipAddress: 10.0.2.14
        n9if:
          ipAddress: 10.100.50.227
      n3network:
        enabled: true
        name: n3network
        type: ipvlan
        masterIf: eth0
        subnetIP: 10.100.50.232
        cidr: 29
        gatewayIP: 10.100.50.238
        excludeIP: 10.100.50.238
      n4network:
        enabled: true
        name: n4network
        type: ipvlan
        masterIf: eth0
        subnetIP: 10.100.50.240
        cidr: 29
        gatewayIP: 10.100.50.246
        excludeIP: 10.100.50.246
      n6network:
        enabled: true
        name: n6network
        type: ipvlan
        masterIf: eth1
        subnetIP: 10.0.2.0
        cidr: 24
        gatewayIP: 10.0.2.2
        excludeIP: 10.0.2.254
      n9network:
        enabled: true
        name: n9network
        type: ipvlan
        masterIf: eth0
        subnetIP: 10.100.50.224
        cidr: 29
        gatewayIP: 10.100.50.230
        excludeIP: 10.100.50.230


# These parameters can be used to enable/disable deployment of subcharts
deployMongoDb: true
deployAmf: true
deployAusf: true
deployChf: true
deployN3iwf: false
deployNef: true
deployNrf: true
deployNssf: true
deployPcf: true
deploySmf: true
deployUdm: true
deployUdr: true
deployUpf: true
deployWebui: true
deployDbPython: true

# Disable the deployment of mongodb as an NRF subchart
free5gc-nrf:
  db:
    enabled: false

# This section can be used to override the default values in the MongoDB chart
mongodb:
  fullnameOverride: "mongodb"
  useStatefulSet: true
  auth:
    enabled: false
  persistence:
    size: 6Gi
    mountPath: /bitnami/mongodb/data/db/
  service:
    name: mongodb
    type: ClusterIP
    port: 27017
    nodePort: "30017"
