#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.gnb }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    app: {{ $.Values.projectName }}
    component: {{ .name }}
data:
  gnb-config.yaml: |

    {{- .configuration | nindent 4 }}
    
    linkIp: GNB_POD_IP   # gNB's local IP address for Radio Link Simulation
    ngapIp: GNB_POD_IP   # gNB's local IP address for N2 Interface
    gtpIp: GNB_POD_IP    # gNB's local IP address for N3 Interface
    
    # List of AMF address information
    amfConfigs:
      - address: {{ $.Values.global.free5gcReleaseName }}-{{ .amf.n2if.serviceName }}
        port: {{ .amf.n2if.port }}

  wrapper.sh: |
    #!/bin/sh
    set -e
    
    # Get Pod IP dynamically
    POD_IP=$(hostname -i | awk '{print $1}')
    echo "[gNB wrapper] Pod IP detected: $POD_IP"
    
    # Copy config to writable location
    cp /ueransim/config/gnb-config.yaml /tmp/gnb-config.yaml
    
    # Replace POD_IP placeholder
    sed -i "s/GNB_POD_IP/$POD_IP/g" /tmp/gnb-config.yaml
    
    echo "[gNB wrapper] Configuration prepared:"
    cat /tmp/gnb-config.yaml | grep -E "linkIp|ngapIp|gtpIp"
    
    # Execute gNB
    exec ./nr-gnb -c /tmp/gnb-config.yaml

{{- end }}
{{- end }}
