#
# Software Name : free5gc-compose
#
{{- with .Values.chf }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-chf.fullname" $ }}-service
  labels:
    {{- include "free5gc-chf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
    - port: 3868
      targetPort: 3868
      protocol: TCP
      name: abmf-diameter
    - port: 3869
      targetPort: 3869
      protocol: TCP
      name: rf-diameter
  selector:
    {{- include "free5gc-chf.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
{{- end}}
---
{{- with .Values.global}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .cgf.service.name }}
  labels:
    {{- include "free5gc-chf.labels" $ | nindent 4 }}
    project: {{ .projectName }}
    nf: {{ $.Values.chf.name }}
spec:
  type: {{ .cgf.service.type }}
  ports: 
    - port: {{ .cgf.service.port }}
      targetPort: {{ .cgf.service.port }}
      protocol: TCP
      name: {{ .cgf.service.name }}
  selector:
    {{- include "free5gc-chf.selectorLabels" $ | nindent 4 }}
    project: {{ .projectName }}
    nf: {{ $.Values.chf.name }}
{{- end}}
